### ISSUE TITLE
New copy for TOTP

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-two-factor#104]
See discussion https://github.com/WordPress/wporg-two-factor/pull/100#issuecomment-1487757380.

We need a new copy for TOTP. If we'd like to keep it as two steps, the copy should be richer in the intro screen. Otherwise, the text needs to be reduced. ([ref](https://github.com/WordPress/wporg-two-factor/pull/100#issuecomment-1489823119))

**Comment by outdoor2kode** [comment]
@jasmussen @StevenDufresne How do these two look to you?

1. 
![Screen Shot 2023-04-14 at 10 34 32 AM](https://user-images.githubusercontent.com/18050944/231927235-cae6f4ec-561b-417d-868d-dc78e8ed8355.png)

2. **With a short intro at the beginning.**
<img width="782" alt="image" src="https://user-images.githubusercontent.com/18050944/231927636-882b7ffa-a86a-4657-ab2b-3fbab7a88ba9.png">

#### How it looks when switching to manual setup
![Screen Capture on 2023-04-14 at 10-46-38](https://user-images.githubusercontent.com/18050944/231929054-97ff6658-a5dc-4b95-8d06-612d8283e2dd.gif)

**Comment by jasmussen** [comment]
Looks okay to me. The input colors, are those the standard input colors? If yes that's good. In the future as we roll out the new colors we'll want to update those to #757575.

**Comment by outdoor2kode** [comment]
> are those the standard input colors? If yes that's good. In the future as we roll out the new colors we'll want to update those to #757575.

Yeah, they are currently standard input colors. Is #757575 expected to apply to only `input[type=text]`?

**Comment by jasmussen** [comment]
If you're using colors from the existing color system that's good for now. I'm also wrong — #757575 is the 4.5:1 _lightest allowed_ text color we use in the block editor, usually for help-text or secondary elements. The block editor uses neutral grays, but for wp.org we'd be using the ones from [the wp.org design library](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=848%3A1740&t=6waiLP5PRlDw0WbH-1), so for similar help-text or secondary elements, in this case the inactive steps, we'd likely use Charcoal 5. Apologies for the misdirection!
