### ISSUE TITLE
Scan QR Code - Clearing input should remove error state.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#106]
When the inputs are cleared, the error state should  be cleared.

## Screenshot
<img width="477" alt="Screenshot 2023-04-18 at 1 34 48 PM" src="https://user-images.githubusercontent.com/1657336/232672667-5c40365a-8c94-49ef-a7da-309627b48ea2.png">

## Test
1. Enter random digits
2. Notice all the fields go red
3. Clear all inputs, notice they are still red.

**Comment by outdoor2kode** [comment]
Where did you see it? It's supposed not to happen on `trunk` as https://github.com/WordPress/wporg-two-factor/pull/100 already handled it. Can you try it again on ~https://github.com/WordPress/wporg-two-factor/pull/112~ trunk?

**Comment by StevenDufresne** [comment]
I'm still getting it on trunk@fbfafc08f6a6f7fa3471445305ccaabedc1cc09b

**Comment by StevenDufresne** [comment]
Ah, I see, when the inputs are cleared with the backspace.

![Screen Capture on 2023-04-20 at 10-24-33](https://user-images.githubusercontent.com/1657336/233233857-6dc83cfc-78b2-43a5-b42d-b428eeea35fc.gif)

**Comment by outdoor2kode** [comment]
Ah, didn't try this scenario, thanks!
