### ISSUE TITLE
Setup: What does blue line indicate?

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#107]
There is a blue line at the top that cuts through the icons. It doesn't progress with the wizard. Is it supposed to be an indicator?

|  | |
| --- | --- |
|<img width="763" alt="Screenshot 2023-04-18 at 1 33 52 PM" src="https://user-images.githubusercontent.com/1657336/232673183-5e35ec3c-5b51-4709-a401-62c7152237c1.png"> | <img width="767" alt="Screenshot 2023-04-18 at 1 42 36 PM" src="https://user-images.githubusercontent.com/1657336/232673375-3193002c-43e6-4186-bde0-343a66079a23.png"> |

**Comment by outdoor2kode** [comment]
With the intro section removed in https://github.com/WordPress/wporg-two-factor/pull/112 after a new copy is applied, the issue will be gone.

https://user-images.githubusercontent.com/18050944/232844354-6520f0bd-66f2-4d98-a55c-0f6f9e239731.mp4

**Comment by outdoor2kode** [comment]
Issue no longer exists after https://github.com/WordPress/wporg-two-factor/pull/112 was merged.
