### ISSUE TITLE
Scan QR Code "back" navigation isn't clear.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#108]
The cancel in relation to the "previous" doesn't make sense. I think we need to do one of the following:

1. Change "cancel" to "clear", move the "previous" button on the left of the UI
2. Remove the "cancel" button, move the "previous" button on the left of the UI

### Screenshot
<img width="450" alt="Screenshot 2023-04-18 at 1 44 36 PM" src="https://user-images.githubusercontent.com/1657336/232674667-c701e1dc-76bc-42fd-94bc-63e70fe8630d.png">

**Comment by outdoor2kode** [comment]
Fixed in https://github.com/WordPress/wporg-two-factor/pull/112
