### ISSUE TITLE
Generated new code dumps you into setup flow.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#109]
When you click "generate new backup codes" you get dumped into the original setup flow:

## Expected Behavior
We should probably just omit the progress indicator when not going through the wizard.

## Screenshot
<img width="450" alt="Screenshot 2023-04-18 at 2 08 53 PM" src="https://user-images.githubusercontent.com/1657336/232677252-2e60fd96-f9f9-4cb3-b69c-69d944f810b6.png">

## Test
1. Complete the setup wizard
2. Visit `/users/{username}/edit/account/?screen=backup-codes` and click "generate new backup codes"
3. Notice you end up back in the initial flow.

**Comment by outdoor2kode** [comment]
The progress indicator has been removed in cb944e53cca8d5e9d75d12b750021d2c3fbc59f3
