### ISSUE TITLE
A11y Audit

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-two-factor#110]
**Keyboard**

- [x] Interactive controls are keyboard focusable.
    - [x] Reasonable DOM order.
    - [x] Non-interactive content should avoid focusable.
- [x] User focus is not accidentally trapped in a region.

**Screen Reader**

- [x] Custom controls have ARIA roles.
- [x] Offscreen content is hidden from assistive technology.
- [x] Clear page structure. (h1-h3 hierarchy is clear)
~HTML5 landmark elements are used to improve navigation.~

**Interactive elements should be distinguishable**

- [x] Ensure link `WordPress/wporg-two-factor on GitHub` is distinguished from surrounding text in a way that does not rely on color.

**Comment by StevenDufresne** [comment]
Let's run this audit before launch. We can prioritize the outcomes in separated tickets.

**Comment by outdoor2kode** [comment]
There aren't any major issues with the results of automated testing tools, but there are still additional items that automated testing tools cannot cover, which we can manually check. (Added to the checklist above)

![Screen Shot 2023-04-20 at 12 32 03 AM](https://user-images.githubusercontent.com/18050944/233141804-75b7303a-f0c9-4336-829b-5e392b4feb1d.png)
![image](https://user-images.githubusercontent.com/18050944/233141944-a34e2c8d-3e68-406f-a43a-4b6d58ff9e3f.png)
![Screen Shot 2023-04-20 at 12 29 09 AM](https://user-images.githubusercontent.com/18050944/233142271-ddb26e99-49f6-4b23-beaa-d3033661961f.png)
