### ISSUE TITLE
Show password strength indicator only submit & failure

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#118]
We currently show the error message as soon as a single character is entered into the password field and even when the password field is empty. This is distracting for a user who is typing a password.

My initial reaction is that, we should probably only show on submit until we have a better inline solution for password feedback. 
We could also throttle the callback so it's only called after we _think_ the user has completed typing their password or is closer to.

Other opinions?

### GIF
![Screen Capture on 2023-04-20 at 10-37-25](https://user-images.githubusercontent.com/1657336/233235982-f746eade-7079-40ff-9219-1fb559d2acc0.gif)

**Comment by outdoor2kode** [comment]
> even when the password field is empty.

Fixing this would be of help on this [issue](https://github.com/WordPress/wporg-two-factor/issues/117) using the method mentioned [here](https://github.com/WordPress/wporg-two-factor/issues/117#issuecomment-1515693367). Currently, the notice won't be gone even if the field is empty.

> My initial reaction is that, we should probably only show on submit until we have a better inline solution for password feedback.

yeah, feel so, as it's a notice, probably better off showing after clicking submit. A password strength indicator would be a more suitable UI to reflect password status instantaneously.

> We could also throttle the callback so it's only called after we think the user has completed typing their password or is closer to.

👍

**Comment by iandunn** [comment]
Yeah, I agree w/ everything Ren said 👍🏻
