### ISSUE TITLE
PHPUnit tests failing

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#140]
```
There were 2 failures:

1) Test_WPorg_Two_Factor::test_set_primary_provider_for_user
Failed asserting that two strings are not identical.

wporg-two-factor/tests/test-wporg-two-factor.php:250

2) Test_WPorg_Two_Factor::test_totp_key_upgraded_to_encrypted
Failed asserting that two strings are not identical.

wporg-two-factor/tests/test-wporg-two-factor.php:290

FAILURES!
Tests: 13, Assertions: 48, Failures: 2.
Script phpunit --no-coverage handling the test event returned with error code 1
```

It looks like those were introduced in aae7ec97a9a8ee22342476f2e0bc78ac3ff4aa3c, cc @dd32. Let me know if the environment is still making it difficult to get the tests setup. I've got it working locally and am happy to take a look.

**Comment by dd32** [comment]
@iandunn I've got local tests running, and they seem fine. Seems fine on the latest run via GitHub actions; https://github.com/WordPress/wporg-two-factor/actions/runs/4821014046/jobs/8586297476#step:8:33 Seems likely either I broke it upstream (but the unit tests are working there) or it's a local issue to you.

**Comment by dd32** [comment]
Actually I suspect this is the result of running with an old `wporg-mu-plugins`, I'm not sure how to properly update the composer dependencies, but I've `rm -rf`'d the composer settings to do that before..

**Comment by iandunn** [comment]
Ah, ok, that makes sense. I'll look into fixing that locally to confirm, and then close the issue 👍🏻
