### ISSUE TITLE
The barcode hover overlaps with copy.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#163]
In production, the hover state for the barcode control overlaps the copy.

URL: `https://wordpress.org/support/users/{username}/edit/account/?screen=totp`

## Screenshots
<img width="507" alt="Screenshot 2023-05-15 at 3 32 00 PM" src="https://github.com/WordPress/wporg-two-factor/assets/1657336/2ac3b9b5-936e-44bf-9aae-9ea8628a6b48">

**Comment by iandunn** [comment]
🤔 I can't reproduce that in Firefox `114.0b7` or Chrome `113.0.5672.126`. Which browser and breakpoint did you see it in? Are you still seeing it on `trunk`?

**Comment by StevenDufresne** [comment]
I'm still seeing it in production:

Chrome: Version `113.0.5672.126`
MacOs: Ventura 13.2.1

It seems to be the fixed height causing it:
https://github.com/WordPress/wporg-two-factor/blob/2331c8a03dee958f0f338acb46243c49c542fa98/settings/src/components/totp.scss#L70

The `SVG` has a height, I wonder why the parent container needs a rule. Introduced in https://github.com/WordPress/wporg-two-factor/commit/35d524f288a8af424503718d2c9e372426eb215d. @renintw Any idea?

**Comment by iandunn** [comment]
Ah, I think the problem is that the SVG size varies a little based on the data inside the QR code. A short username in [`$totp_title`](https://github.com/WordPress/two-factor/blob/654ebb75024c21c116b4155e7254e143c9f64413/providers/class-two-factor-totp.php#L234) would generate a shorter SVG than a long one.

The fixed height may have been an attempt to protect against that?

**Comment by outdoor2kode** [comment]
> Ah, I think the problem is that the SVG size varies a little based on the data inside the QR code. A short username in [$totp_title](https://github.com/WordPress/two-factor/blob/654ebb75024c21c116b4155e7254e143c9f64413/providers/class-two-factor-totp.php#L234) would generate a shorter SVG than a long one.

Ah, that's really the case! Great observation.

> The SVG has a height, I wonder why the parent container needs a rule. Introduced in https://github.com/WordPress/wporg-two-factor/commit/35d524f288a8af424503718d2c9e372426eb215d. @renintw Any idea?

Initially, I added the fixed height to make the width and height of the QR code consistent, so as not to affect the space between components and to comply with the Figma design.
