### ISSUE TITLE
Incorrect color for interactive elements with Gutenberg 15.8

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-two-factor#167]
`--wp-admin-theme-color` seems to have changed to blueberry, and all the elements using it now don't match the rest of the UI

![Screen Shot 2023-05-19 at 12 01 57 PM](https://github.com/WordPress/wporg-two-factor/assets/1017872/ba72d4fa-37c5-4121-820c-8abbd5a7172c)

![Screen Shot 2023-05-19 at 12 05 43 PM](https://github.com/WordPress/wporg-two-factor/assets/1017872/c461be5f-426d-46a6-bff3-4424bb9eeefa)

**Comment by adamwoodnz** [comment]
It seems this might be related to style loading order. Prod styles are inline, whereas local is not and the plugin styles are loading before Gutenberg (even though `wp-components` is listed as a dependency), so that might be the cause. Need to check sandbox with Gutenberg 5.8

**Comment by adamwoodnz** [comment]
[This PR](https://github.com/WordPress/gutenberg/pull/50193) looks to be the cause

**Comment by StevenDufresne** [comment]
@adamwoodnz What needs to be done here?

**Comment by adamwoodnz** [comment]
> @adamwoodnz What needs to be done here?

I'm undecided on the way forward. It only seems to affect local dev, where the `wp-component` styles load after the block styles, even though they are supposed to be a dependency. This doesn't happen in production (not using 15.8 yet) or sandbox. That seems like it might be a Gutenberg bug, or a bug with our setup, but I haven't found an existing Gutenberg issue.

As such the recommended fix in this [PR](https://github.com/WordPress/wporg-two-factor/pull/184) doesn't work, as the var still gets overridden. 

Only the `@wordpress/components` has had this change to the `--wp-admin-theme-color` var committed so far, but I imagine others might follow, so the problem might become more widespread.

So we could ignore it locally, but it would affect any styling work we're doing.

Another option which I tried successfully was overriding the var but scoped to only our components, so that we don't affect the global header or footer, for example. Something like:

```
.wp-block-wporg-two-factor-settings {
	--wp-admin-theme-color: #007cba;
}
```

Seems a reasonable workaround, thoughts?

**Comment by StevenDufresne** [comment]
I would be tempted to leave it alone although I'm not sure if support will get an update in the redesign. I imagine it will.

**Comment by adamwoodnz** [comment]
Closing due to low impact and low priority. We can reopen if needed.
