### ISSUE TITLE
"Primary" isn't being respected as preferred 2fa method.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#171]
I have both one time passwords and WebAuthn configured. If I set the "primary" to WebAuthn, it still uses one time passwords.

## Screenshot
<img width="561" alt="Screenshot 2023-05-22 at 11 19 08 AM" src="https://github.com/WordPress/wporg-two-factor/assets/1657336/d236d66b-8490-48f9-bcaa-9fb6247fd3c4">

**Comment by dd32** [comment]
This UI is mostly irrelevant, as it's only currently enabled currently to allow access to the WebAuthN settings, until #87 (The UI) is finalised.
_(We should probably consider enabling the WebAuthN settings through firing the action, but hiding the Two-Factor UI parts)_

However, based on WebAuthN being forced as a preference over TOTP in code, I'm lead to believe you're likely hitting the Two-Factor revalidate code that prefers the same method as what you previously used.

To confirm; Where are you seeing it not preferring WebAuthN?

**Comment by StevenDufresne** [comment]
After clearing my env and using production, i wasn't able to replicate. Closing.
