### ISSUE TITLE
Reauth required immediately after reactivating 2FA

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-two-factor#173]
Steps to reproduce:

1. Enable 2FA
2. Take note of the time when revalidation will be required based on the timestamp at `user.userRecord.record['2fa_revalidation']` 
3. Disable 2FA
4. After the `2fa_revalidation` time has passed, re-enable 2FA

Expected behaviour: notification that 2FA was enabled successfully displayed, no modal displayed

Actual behaviour: modal prompting to reauth displayed

![Screen Shot 2023-05-23 at 12 36 50 PM](https://github.com/WordPress/wporg-two-factor/assets/1017872/0ccff08c-71cb-4a31-85d1-a19ae3547905)

It seems that the `2fa_revalidation` timestamp is stale and hence the modal pops up because there is now a primary provider. The logic is [here](https://github.com/WordPress/wporg-two-factor/blob/trunk/settings/src/script.js#L164)

**Comment by dd32** [comment]
This seems likely tightly coupled with #179
