### ISSUE TITLE
User couldn't turn off authentication because of re-auth and backend code didn't work.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#179]
A user turned on 2fa, and got stuck generating backup codes. They essentially never completed. 

This left the user in this state:

<img src="https://github.com/WordPress/wporg-two-factor/assets/1657336/41daa929-226e-4c3b-b797-01b92e8e967a" width="400">

Since they timed out, the user was not able to regenerate them.

I asked them to turn off 2fa, when they tried they got this error:

<img src="https://github.com/WordPress/wporg-two-factor/assets/1657336/9d50f7f3-449d-4e59-a4b5-9ef72e77993c" width="400">

They were finally able to complete everything after using Incognito Mode.

## Environment
Windows 11,
Microsoft Edge 113

**Comment by dd32** [comment]
I was able to duplicate this, and found these console logs:

```
[Error] Failed to load resource: the server responded with a status of 500 () (generate-backup-codes, line 0) https://wordpress.org/support/wp-json/two-factor/1.0/generate-backup-codes?_locale=user
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (script.js:1:19075)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

> I asked them to turn off 2fa, when they tried they got this error:

I can also confirm this, It appears this would be the same error as what is preventing the backup codes to be regenerated, it's just that we're missing a failure handler.

Looking at the session metadata (`Two_Factor_Core::get_current_user_session()`), I can see this is caused by our custom UI not setting the session metadata that flags the session as 2fa: https://github.com/WordPress/two-factor/blob/654ebb75024c21c116b4155e7254e143c9f64413/class-two-factor-core.php#L1848-L1864 (This entire function is not run in our setup)

**Comment by dd32** [comment]
>  I can see this is caused by our custom UI not setting the session metadata that flags the session as 2fa

The upstream code is handled within the general `update settings` handler, but I could see an arguement to be made that it should also be within the `enable this provider for the user` code branch. @iandunn what's your thoughts here? Should we focus on an upstream fix here (in addition to the quick fix we apply to this repo)

**Comment by pkevan** [comment]
I was able to reproduce what I assume is the same issue, and appears tied to the revalidation logic, this is the response from the API request, which returns a `500` status code:

`{"code":"revalidation_required","message":"Two Factor Revalidation required.","data":null}`

**Comment by benniledl** [comment]
> I was able to reproduce what I assume is the same issue, and appears tied to the revalidation logic, this is the response from the API request, which returns a `500` status code:
> 
> `{"code":"revalidation_required","message":"Two Factor Revalidation required.","data":null}`

I have the same problem and the same reponse as you.

**Comment by iandunn** [comment]
> I could see an arguement to be made that it should also be within the enable this provider for the user code branch. 

Yeah, that makes sense to me 👍🏻

**Comment by dd32** [comment]
> I was able to duplicate this, and found these console logs:
> 
> [Error] Failed to load resource: the server responded with a status of 500 () (generate-backup-codes, line 0) 

This part is being worked on via #182
