### ISSUE TITLE
Refine WebAuthn visual design

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#194]
#95 stubbed in the rough code and UI, and #193 added real data/functionality.

In this PR we should refine that UI to match @jasmussen 's [design](https://github.com/WordPress/wporg-two-factor/pull/95#issuecomment-1563945641). I think Steve's idea of [a `Primary` indicator](https://github.com/WordPress/wporg-two-factor/pull/95#issuecomment-1563656017) is helpful too.

Canonical Figma:

* [checklist state 1](https://www.figma.com/file/6KPZbXujMGDRWWDR5odjDE/WP.org-improvements-%2F-QA?type=design&node-id=565-8992&t=Z1tueC4WkO24WnR5-4)
* [checklist state 2](https://www.figma.com/file/6KPZbXujMGDRWWDR5odjDE/WP.org-improvements-%2F-QA?type=design&node-id=565-12287&t=Z1tueC4WkO24WnR5-4)
* [security key flow](https://www.figma.com/file/6KPZbXujMGDRWWDR5odjDE/WP.org-improvements-%2F-QA?type=design&node-id=565-11747&t=Z1tueC4WkO24WnR5-4)
* [animation](https://www.figma.com/file/6KPZbXujMGDRWWDR5odjDE/WP.org-improvements-%2F-QA?type=design&node-id=565-12135&t=Z1tueC4WkO24WnR5-4)

**Comment by iandunn** [comment]
Hey @jasmussen 👋🏻  I noticed a few differences between this and the TOTP flow:

* After setting up TOTP, the user is redirected to Backup Codes, but here they're redirected back to the Security Keys intro screen.
* TOTP adds a snackbar-esque notice on success, but this doesn't.
* TOTP has a button to disable it, but this doesn't.

Should the two screens be more consistent? What do you think about both screens redirecting to Backup Codes if they're not already setup, but back to the totp/security-key screen if backup codes are already setup?

**Comment by jasmussen** [comment]
Any discrepancies are very likely to mainly be my lack of full understanding of the flow, so no reason to make too big of a detour. If you can provide me with screenshots of the flow, I'm happy to adjust, provide the remaining screens, or give feedback if perhaps we can optimize a part of it.

**Comment by adamwoodnz** [comment]
> If you can provide me with screenshots of the flow

@jasmussen here are the differences

> TOTP has a button to disable it, but this doesn't.

The `Disable security keys` button below isn't shown in the designs, but to be consistent with TOTP we could add it.

| TOTP | Security Keys |
|-|-|
| ![Screenshot 2023-08-08 at 3 07 57 PM](https://github.com/WordPress/wporg-two-factor/assets/1017872/092bc05f-c9fa-40ae-b41e-fb0019699b72) | ![Screenshot 2023-08-08 at 3 08 09 PM](https://github.com/WordPress/wporg-two-factor/assets/1017872/c68a1ad7-85ab-46b9-a11b-9bddd4e8c711) |

> After setting up TOTP, the user is redirected to Backup Codes, but here they're redirected back to the Security Keys intro screen.
> TOTP adds a snackbar-esque notice on success, but this doesn't.

After successfully adding an app or registering a key, the final destination screens look like this:

| TOTP -> Backup codes | Security Keys -> list screen |
|-|-|
| ![Screenshot 2023-08-08 at 3 24 42 PM](https://github.com/WordPress/wporg-two-factor/assets/1017872/4b55b479-e778-43ed-8e39-17d805518642) | ![Screenshot 2023-08-08 at 3 27 51 PM](https://github.com/WordPress/wporg-two-factor/assets/1017872/af56ee52-9090-42be-b677-2a65f7edf929) |

**Comment by jasmussen** [comment]
From those screenshots, it looks like a decent enough starting point to me. I might have used the tertiary style for "Disable security keys" since it sits next to a primary button, but the secondary style works okay 👍 👍

**Comment by adamwoodnz** [comment]
@jasmussen what do you think about the end of the flow; should we redirect to the Backup Codes screen with the success notification (like TOTP), or is it better to stay on the list screen?

IMO a success notification feels like it should be added in both cases.

**Comment by jasmussen** [comment]
Is that partially covered by this sketch?

<img src="https://user-images.githubusercontent.com/1204802/241151296-f2a79b70-9832-4021-aa67-593f1b09e535.png">

If yes, the idea there was to show a spiner, then a success animation, then after n seconds, redirect back.

**Comment by adamwoodnz** [comment]
> show a spiner, then a success animation, then after n seconds, redirect back

Oh yes, let's go with that then, maybe the success animation can replace all the success notices we currently use

**Comment by jasmussen** [comment]
> maybe the success animation can replace all the success notices we currently use

If the actions are _small and not too substantial_, I think a notice/snackbar can be fine. 

In the flow suggested above, the animation exists because the action is a bit more substantial, i.e. connecting a security key. I imagine scanning a QR code is also a substantial action. Deleting a key, or something like that, would not be substantial and can just be confirmed more simply.
