### ISSUE TITLE
Design: Main View

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#198]
Related: #194 

The landing page currently looks like this configured: <img width="780" alt="Screenshot 2023-05-30 at 12 59 35 PM" src="https://github.com/WordPress/wporg-two-factor/assets/1657336/62f6dde4-9242-4a73-aaba-9b530f5bda4d">

I don't understand the use of ✔️ since the first two items aren't things that are _complete_ and the backup codes are technically verified by the process of "saving" them but the check doesn't mean anything because it really isn't reversible. Since we are looking at this view in [WebAuthn updates](https://github.com/WordPress/wporg-two-factor/pull/95#issuecomment-1563945641), I was wondering if we could use an icon instead of the check. Something like this:

  
<img width="765" alt="Screenshot 2023-05-30 at 1 09 48 PM" src="https://github.com/WordPress/wporg-two-factor/assets/1657336/f449bfa7-c070-4e9f-af97-6a310a8ce829">

cc: @WordPress/meta-design

**Comment by jasmussen** [comment]
> I don't understand the use of ✔️ since the first two items aren't things that are complete and the backup codes are technically verified by the process of "saving" them but the check doesn't mean anything because it really isn't reversible.

From my instincts in designing this, it's a "security" setting, and in having checks next to the boxes you can at a glance see which security settings you _haven't yet_ completed (the checks all being the same make the odd ones stand out). In that sense, the email address (which I'm assuming is validated by an email link challenge) is where you can get your password resets, and the password we can assume is strong enough to earn the check, lest we can show the cross as an action item perhaps.

**Comment by StevenDufresne** [comment]
Okay, fair enough. Thanks for weighing in. I don't feel strongly about this as a result so I'll close it for now.
