### ISSUE TITLE
Only allow backup codes when another 2FA method exists

### ISSUE THREAD

**Issue by pkevan** [WordPress/wporg-two-factor#21]
Currently you can setup backup codes without an additional method (TOTP, auth key). 

If we want to block this workflow, and tie backup codes to only be used as an additional method, then we'll need to rework the logic and possibly restrict backup codes being a primary method.

**Comment by pkevan** [comment]
Related: #15

**Comment by pkevan** [comment]
See: https://github.com/pkevan/two-factor/commit/0f6ee66d3c2136a430d2d37655b432795f70748e

**Comment by iandunn** [comment]
Related #23 

> See: https://github.com/pkevan/two-factor/commit/0f6ee66d3c2136a430d2d37655b432795f70748e

Was that meant to be posted to #22?

If we're writing a custom UI from scratch, I wonder if it'd be better to use React and Gutenberg components/utilities, instead of jQuery/etc?

**Comment by pkevan** [comment]
> Was that meant to be posted to https://github.com/WordPress/wporg-two-factor/issues/22?

Yes! Good catch :)

**Comment by pkevan** [comment]
> If we're writing a custom UI from scratch, I wonder if it'd be better to use React and Gutenberg components/utilities, instead of jQuery/etc?

Probably, i'm just prototyping the functionality and following pre-existing patterns in the plugin.

**Comment by pkevan** [comment]
We can probably achieve this using the `two_factor_providers` filter.

**Comment by pkevan** [comment]
https://github.com/WordPress/wporg-two-factor/pull/24 as a potential method for doing this.

**Comment by TobiasBg** [comment]
I only found this repo after opening a ticket in Meta Trac, but for reference: https://meta.trac.wordpress.org/ticket/6825

**Comment by iandunn** [comment]
Hey 👋🏻 , sorry you experienced that. https://github.com/WordPress/two-factor/issues/507 is the main cause for it, but #75 and #47 will help mitigate it in the mean time.

**Comment by TobiasBg** [comment]
Hi @iandunn, thanks for the context! Yes, that sounds exactly like what happened. The fix sounds reasonable to me as well. (I'm all set again already, thanks to a forums moderator.)

**Comment by outdoor2kode** [comment]
I guess we can close this issue for now since #75 has already been merged and #47 can stand on its own.
@iandunn @pkevan  If you feel it's necessary, please feel free to reopen it.
