### ISSUE TITLE
Unable to see the first set of backup codes after completing the 2FA application

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-two-factor#216]
After completing the 2FA application and entering the backup codes screen, the user is taken to the Manage screen the moment the codes are generated, making the user unable to see the current codes.

https://github.com/WordPress/wporg-two-factor/assets/18050944/28bb0f27-6f2b-482a-ad4e-18e9164387da

**Comment by iandunn** [comment]
🤔 I'm not seeing this behavior locally. Do you still see it with the latest `trunk`?

**Comment by outdoor2kode** [comment]
>  I'm not seeing this behavior locally. Do you still see it with the latest trunk?

I couldn't reproduce this behavior locally as in fact, I couldn't activate 2fa in my local env. Not sure if it was only me or if someone else also ran into this in their local env as well. If it's only me, I guess it has something to do with the [DB configuration](https://a8c.slack.com/archives/G010HCMN0HF/p1685393231050339) earlier.

I didn't dive deep into it for this issue as this one can also be reproduced while sandboxed or on production, the screencast above was from the production. And I can still reproduce it on production which was just deployed with the latest commit on `trunk` not long ago.

![Screen Capture on 2023-06-15 at 11-56-02](https://github.com/WordPress/wporg-two-factor/assets/18050944/ebca8d4e-d1ed-4c77-8e4a-015b9e045fc6)
