### ISSUE TITLE
Not redirected to Backup Codes after enabling WebAuthn

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#253]
1. Wipe out all settings/providers so you start fresh
2. Enable TOTP. You're redirected to Backup Codes
1. Wipe out all settings/providers so you start fresh
1. Enable WebAuthn. You're not redirected to Backup Codes

For consistency, I think we should add something like this to WebAuthn
    https://github.com/WordPress/wporg-two-factor/blob/fa4c81b35d0c6b8fe75723ee2529299a0b2e767e/settings/src/components/totp.js#L25-L28

**Comment by dd32** [comment]
#286 might resolve this.

Alternatively, given you can enable multiple keys, perhaps simply a notice at the bottom of the keys screen suggesting "All done? Set some Backup codes".

This is IMHO one of the reasons why it's common to be presented with the backup codes **prior** to setting up any 2FA methods.
