### ISSUE TITLE
Turn off 2 step authenticator.

### ISSUE THREAD

**Issue by MarieAliceD** [WordPress/wporg-two-factor#259]
trying to change phone number on 2 step authenticator. I cannot find the print with the WP codes. I am able to ac-cess my website dashboard but not the WP account ! WHere can I change my mobile number on the WP-admin ? Cannot see the "security" option !

**Comment by iandunn** [comment]
Hi, wordpress.org doesn't collect phone numbers, are you using wordpress.com?

It's confusing, but they're a separate organization, and you'll need to contact them for support.

https://wordpress.org/documentation/article/difference-between-wordpress-org-and-wordpress-com/

I'm going to go ahead and close this, but let me know if I misunderstood and we can reopen it.
