### ISSUE TITLE
Request for Deleting Account on WordPress.org

### ISSUE THREAD

**Issue by ghost** [WordPress/wporg-two-factor#272]
Hallo,

I would like to delete a new account I created on wordpress.org today, but I can not find the option for doing so anywhere in the account settings.

Therefore, may I ask you for either deleting the account straight away or sending me a link to do so?

I have attached the details from the account and confirmation e-mail below.

Thanks a lot,

[redacted]

Profile
[account redacted]
Member Since: [redacted]

**Comment by StevenDufresne** [comment]
Hi.

In order to delete an account, you need to submit an official data erasure request here:
https://wordpress.org/about/privacy/data-erasure-request/
