### ISSUE TITLE
UI: Language 

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#29]
Implement the language field in the custom UI, see #18 for rough mockups

**Comment by dd32** [comment]
What does this Language selector actually do?

AFAIK it probably only controls the wp-admin locale - if so, we can ditch this field.

**Comment by iandunn** [comment]
Yeah, it's just the user locale setting. I would guess that there's some front end stuff that it affects as well, like learn.wordpress.org and a few other places that have front-end localization. It seems like it'd be important to keep, since we're planning for more of that in the future. Does that seem right to you?

**Comment by dd32** [comment]
> I would guess that there's some front end stuff that it affects as well, like learn.wordpress.org and a few other places that have front-end localization.

If that were the case, yeah, I would agree with keeping it.

However, it's not actually used anywhere other than `wp-admin` at present that I'm aware of, including learn.w.org.

The thing it affects is `get_user_locale()` which is only used for the requests within wp-admin by default in https://developer.wordpress.org/reference/functions/determine_locale/ 

Looking closer, it looks like all plugins on dotorg only use it within wp-admin, aside from the Pattern Directory which appears to respect it for notifications.

Given it's lack of use, I suggest we skip the field for now, given it doesn't actually affect the majority of users, there's a good chance whatever data we've stored in there might not even be correct.

**Comment by iandunn** [comment]
That WFM 👍🏻
