### ISSUE TITLE
JS + CSS should not be loaded on every page

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-two-factor#35]
As currently expected, the wporg-two-factor settings screen CSS/JS is loaded/output on every page.

```
$ curl -is https://wordpress.org/ | grep wporg-two-factor

<style id='wporg-two-factor-settings-style-inline-css'>
.wp-block-wporg-two-factor-settings h3 {
.wp-block-wporg-two-factor-settings .components-button {
<script src='https://wordpress.org/wp-content/plugins/wporg-two-factor/settings/build/script.js?ver=1672716006' id='wporg-two-factor-settings-script-js'></script>
```

**Comment by iandunn** [comment]
I ran into this as well :( 

https://github.com/WordPress/wporg-two-factor/pull/36/commits/d8e6a9ad39c42e5989defd8537d09fa78d817b2d may help some, but doesn't solve it on by itself.

IIRC Gutenberg solved this problem automatically in https://github.com/WordPress/gutenberg/issues/5445 and some of the related issues, but maybe that's not working for us because we aren't loading it via `post_content` ?

**Comment by dd32** [comment]
> https://github.com/WordPress/wporg-two-factor/commit/d8e6a9ad39c42e5989defd8537d09fa78d817b2d may help some, but doesn't solve it on by itself.

I suspect that would actually make it worse, as they'd now be loaded too, although It doesn't look like that's happening..

> IIRC Gutenberg solved this problem automatically in https://github.com/WordPress/gutenberg/issues/5445 and some of the related issues, but maybe that's not working for us because we aren't loading it via post_content ?

If it was solved through Gutenberg, not using `post_content` would work in the reverse than what it's currently doing - I'd expect the block assets to never be loaded.

It looks like we can switch to `viewScript` in `block.json` to get the script loaded only when rendered, but for styles there's nothing there... See `viewStyle` in https://github.com/WordPress/gutenberg/issues/41236

**Comment by dd32** [comment]
Turns out this is also causing `zxcvbn.min.js` and `qrcode-generator/qrcode.js` to be enqueued.

https://meta.trac.wordpress.org/ticket/6770

**Comment by adamwoodnz** [comment]
Update: All that remains is the CSS now

```
$ curl -is https://wordpress.org/ | grep wporg-two-factor

<link rel='stylesheet' id='wporg-two-factor-settings-style-css' href='https://wordpress.org/wp-content/plugins/wporg-two-factor/settings/build/style-index.css?ver=0.1.0' media='all' />
```
