### ISSUE TITLE
Disable backup codes UI until primary provider enabled

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#47]
Update: The goal of this has shifted, see https://github.com/WordPress/wporg-two-factor/issues/47#issuecomment-1412483300

----

Right now we only allow regenerating backup codes, but not disabling them. The `Disable Two Factor...` button on the TOTP screen only disables TOTP. Should it also disable backup codes, or should the user be able to control them independently?

Related #21

**Comment by dd32** [comment]
IMHO: Backup codes should be disabled automatically once TOTP (or in the future, WebAuthN) is disabled, disabling it shouldn't revoke existing codes though.

IMHO We don't want a user to have 2FA enabled via Backup codes alone.

I don't know how the UI would look like in that case, perhaps it should be disabled during the login process (ie. 2FA is not activated) but the user overview should have a green tick?

**Comment by bengreeley** [comment]
I noticed this as well and am glad there's an issue to address it. As a user who hadn't yet activated 2fa, I was able to click on the 'Two-Factor Backup Codes' option on https://wordpress.org/support/users/bengreeley/edit/account/?screen=account-status , and didn't verify I printed or saved the codes. The next time I logged in, I was prompted to provide a backup code.

I'd think we would want to address two things:
1. Prevent backup codes from being generated unless the user has opted into 2fa.
2. Only count the backup codes as being generated if somebody clicks on the 'I have printed or saved these codes' checkbox.

**Comment by pkevan** [comment]
@bengreeley there is an upstream issue which details what you are suggestion: https://github.com/WordPress/two-factor/issues/507

**Comment by iandunn** [comment]
> Backup codes should be disabled automatically once TOTP [...] is disabled, disabling it shouldn't revoke existing codes though. [...] We don't want a user to have 2FA enabled via Backup codes alone.

That makes sense. #21 covers most of that, so I guess in this issue we'd just want to modify the UI. The Backup Codes screen should probably not be enabled until another provider is. That would prevent accidentally enabling it.

Keeping the green tick and existing backup codes does make sense to me. Maybe we allow the screen to be shown, but it shows a warning instead of the current content. The warning could explain that they need to have another provider enabled in order for backup codes to be enabled.

**Comment by iandunn** [comment]
IMO we still need [the UI warning](https://github.com/WordPress/wporg-two-factor/issues/47#issuecomment-1412483300) for UX. Otherwise the backup codes will still be generated before TOTP is setup, and the user will have to re-generate them if they didn't save them.

**Comment by dd32** [comment]
Agreed, I didn't intend on closing this :)

**Comment by StevenDufresne** [comment]
I think this should be included in the MVP, at least the part where the backup codes look clickable before 2fa has been setup.

**Comment by outdoor2kode** [comment]
I'm moving this to MVP as I reckon the part of the backup code is better off having some good handle to prevent users from accidentally enabling it.

**Comment by adamwoodnz** [comment]
Can we please have some concise requirements added to this? I'd like to pick it up but it's not clear to me exactly what needs to be done.

**Comment by StevenDufresne** [comment]
> Can we please have some concise requirements added to this? I'd like to pick it up but it's not clear to me exactly what needs to be done.

Even though a user hasn't configured their 1fa, they are able to click into the "Generate backup codes" view:

| Default State (GIF) |
| --- |
| ![Screen Capture on 2023-05-11 at 14-38-50](https://github.com/WordPress/wporg-two-factor/assets/1657336/c73463ec-fa3a-4945-b8a8-d06a481e6e49)  |

For the MVP, let's disable the backup code view if 2fa is not setup.

**Comment by iandunn** [comment]
IMO it'd be helpful to also [add a warning](https://github.com/WordPress/wporg-two-factor/issues/47#issuecomment-1412483300), otherwise I'm not sure how the user would understand why backup codes are disabled, or how to enabled them.
