### ISSUE TITLE
Update Site Name in Authenticator App

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-two-factor#48]
When I scan the QR code in my Authenticator app, it appears as ‘WordPress.org Forums’ in the app.

Though this might be accurate for some users who only have an account for the forums, I would expect this to be a bit more generic if it's for the main WordPress website. Could we have the default name be 'WordPress.org' unless it's for a login system that's different than wordpress.org? I believe all the sites on wordpress.org (including Rosetta sites) use the same login screen at login.wordpress.org, so I'd think we would want to default to the name of that site, which could just be WordPress.org.

**Comment by iandunn** [comment]
I agree. Fixed in 17528dc
