### ISSUE TITLE
Draft MVP launch post

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#50]

**Comment by tellyworth** [comment]
Drafted! https://make.wordpress.org/meta/wp-admin/post.php?post=26956&action=edit

**Comment by iandunn** [comment]
Looks good! I made a few tweaks, but this was the only substantial one:

```diff
-You must also download or print Backup Codes before 2FA will be activated on your account.
+Please make sure you save the Backup Codes! 
```

The UI encourages that, but it's not enforced; https://github.com/WordPress/two-factor/issues/507 is a blocker for doing it. Related: #21, #47 

We also haven't added the download/print buttons yet, see https://github.com/WordPress/wporg-two-factor/issues/39#issuecomment-1398555494 and #45
