### ISSUE TITLE
Remove "Cancel" button from "Verify Codes" screen

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#78]
## Reasoning
- The cancel button feels connected to the input, not the page
  - Without looking carefully, it seems like a "clear" button makes more sense. 
- If the user has scanned the bar code and is adding codes to the input, they likely **wouldn't** bail there. Everything in that space should get the verification code complete.
- It would align it with the other screens that don't have a "cancel" button at the bottom.

### Screenshot
<img width="696" alt="Screen Shot 2566-03-10 at 14 03 47" src="https://user-images.githubusercontent.com/1657336/224229411-c35c22bb-6de1-4688-9ed6-5077df8af231.png">

**Comment by iandunn** [comment]
🤔 I wonder if it gives users confidence that they successfully aborted the setup process? Otherwise, someone might think they have to complete the process because they started it, when in reality nothing is saved until the click `Enable`.

Do you have any thoughts @jasmussen?

**Comment by jasmussen** [comment]
This was the original design:

<img width="975" alt="Frame 9" src="https://user-images.githubusercontent.com/1204802/224663471-5f1290ba-f36f-4f0c-b15a-5178fe695f1e.png">

That design doesn't consider the fact that you could press "back" or click any of the other surrounding links. In that light, I could agree with the removal. If the screen had been more empty, i.e. without a back button, it would make more sense. Here's an alternate design:

<img width="760" alt="Frame 10" src="https://user-images.githubusercontent.com/1204802/224665086-3436f07a-389a-4bb9-82da-ca9c2f8530d9.png">

**Comment by StevenDufresne** [comment]
This has fallen out of date. Closing.
