### ISSUE TITLE
Improve Invalid verification code UI

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#80]
The error UI can use some improvement. At the very least just adjust it's padding and make it left align with the content.

## Screenshot

<img width="686" alt="Screen Shot 2023-03-10 at 2 24 17 PM" src="https://user-images.githubusercontent.com/1657336/224230820-d6e97b8f-bb68-4865-b287-4f5f869d6f79.png">

**Comment by iandunn** [comment]
👍🏻 It should apply to other notices as well 

Related #5
