### ISSUE TITLE
Fix a flash of the red "too easy" notice before it shows the success notice

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-two-factor#85]
Ref: https://github.com/WordPress/wporg-two-factor/blob/trunk/settings/src/components/password.js#L48-L51

@iandunn I couldn't reproduce what you described, perhaps I have misunderstood something about it, is it possible to attach some screencasts for it?

**Comment by iandunn** [comment]
🤔 , I can't reproduce it anymore either. The default value of `passwordStrong` changed from `false` to `true` in 0e9017eef0a7c5d24156e11d7c1771fcdcf8849d, so that may have fixed it. 

I think it's fine to remove the comment. I'll open a PR for that 👍🏻
