### ISSUE TITLE
Show the 2fa number larger

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-two-factor#92]
Make the number in the input box larger, and perhaps change to use the `IBM Plex Mono font`

![image](https://user-images.githubusercontent.com/18050944/227377461-517b1522-26b8-4f8e-9f97-3b6f07c892f6.png)

**Comment by outdoor2kode** [comment]
@jasmussen Since the last time you [suggested](https://github.com/WordPress/wporg-two-factor/issues/5#issuecomment-1415629776) changing the style of the number, its style has been changed a bit.

| Before | Now |
| ------ | -----|
| ![image](https://user-images.githubusercontent.com/18050944/227377044-6a976679-7cf0-4a73-a705-ac8a80693066.png) | ![image](https://user-images.githubusercontent.com/18050944/227379903-196d7c88-c211-451a-9a13-367d9ea00ec8.png) |

The comparison image is a bit imbalanced, you might want to click on this link to see it directly. 
`https://wordpress.org/support/users/{your username}/edit/account/?screen=totp`

Font size for the numbers is now `14px`, what size do you think it should be increased to?
And just to confirm, the size of the code text doesn't need to change, right?

Note: I guess we don't need to take care of the size change here with the new look brought up [here](https://github.com/WordPress/wporg-two-factor/issues/93).

**Comment by jasmussen** [comment]
Can you work with this design?

<img width="694" alt="Screenshot 2023-03-27 at 10 15 36" src="https://user-images.githubusercontent.com/1204802/227882220-bef16557-b617-4827-b44a-aa9764fb8e5f.png">

Thanks for the ping.
