### ISSUE TITLE
Split 2FA instruction into two steps

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-two-factor#93]
The content in the 2fa screen is a bit packed together. We may want to split it into two steps. 

One step for the intro:
![image](https://user-images.githubusercontent.com/18050944/227380682-5625b115-51e8-4d1c-967d-61781f7b7b72.png)

And one step for the non-QR code version:
![image](https://user-images.githubusercontent.com/18050944/227380722-a0a12703-37d8-4612-9b5a-072e43f8b607.png)

Another for the text version:
![image](https://user-images.githubusercontent.com/18050944/227380767-029e2d29-c137-462c-adc7-ad0116dd146e.png)

**Comment by outdoor2kode** [comment]
@jasmussen Do we have a Figma link for the new look that you shared?

**Comment by jasmussen** [comment]
Yes, it's a bit messy, but [here](https://www.figma.com/file/vmHxwa8WhiyiP9poe2om9J/Inspector-Panels?node-id=14493%3A128082&t=8l7m2Mm8aoP4YS77-1)

**Comment by outdoor2kode** [comment]
@jasmussen Thanks for the link. I'll work on this new look.
