### ISSUE TITLE
WebAuthn launch items

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-two-factor#94]
#87 is adding stubs for the UI, but they'll only show up in the development build for now. When the backend is in place and we're ready to launch WebAuthn, we'll need to make the following changes. They can't be done now because they'd affect production users.

- [x] Change the TOTP disabled string to `You have not enabled an app for two-factor authentication.` If we don't it will imply they have 2FA disabled if they have webauthn enabled but TOTP disabled.

	https://github.com/WordPress/wporg-two-factor/blob/1956891a71e499e8c1fef39eab1edf10a39d2e05/settings/src/components/account-status.js#L48-L51

- [x] Change `TOTP` screen title from `Two Factor Authentication` to `Two Factor App` or something like that. When webauthn launches TOTP will no longer be the only way to enable 2FA

	https://github.com/WordPress/wporg-two-factor/blob/1956891a71e499e8c1fef39eab1edf10a39d2e05/settings/src/script.js#L142

- [x] Change the WebAuthn screen title from `webauthn` to `WebAuthn`

	https://github.com/WordPress/wporg-two-factor/blob/1956891a71e499e8c1fef39eab1edf10a39d2e05/settings/src/script.js#L142

- [x] Update `primaryProviderEnabled` to include WebAuthn

	https://github.com/WordPress/wporg-two-factor/blob/9973b5f7f07bd6e3e7e1916db0c67a32de28cf37/settings/src/components/account-status.js#LL24C8-L24C30

**Comment by StevenDufresne** [comment]
Does this still apply with design happening in #194 ?

**Comment by iandunn** [comment]
I think all of these were addressed in #95 👍🏻
